# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-pvc
# spec:
#   storageClassName: local-storage
#   volumeName: grafana-pv  # This PVC will bind to a specific PV named "grafana-pv"
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  # volumeName: grafana-pv
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
