apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: nfs-client # must match the StorageClass name in storageclass.yaml
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi