authoritative;
ddns-update-style interim;
allow booting;
allow bootp;
allow unknown-clients;
ignore client-updates;
default-lease-time 14400;
max-lease-time 14400;

subnet 10.0.0.0 netmask 255.255.255.0 {
 option routers                  10.0.0.1; # lan
 option subnet-mask              255.255.255.0;
 option domain-name              "supportlab.local";
 option domain-name-servers       10.0.0.1;
 range 10.0.0.80 10.0.0.99;
}

host ocp-bootstrap {
 hardware ethernet 00:50:56:be:e3:f1;
 fixed-address 10.0.0.200;
}

host ocp-cp-1 {
 hardware ethernet 00:50:56:be:ae:4d;
 fixed-address 10.0.0.201;
}

host ocp-cp-2 {
 hardware ethernet 00:50:56:be:28:5a;
 fixed-address 10.0.0.202;
}

host ocp-cp-3 {
 hardware ethernet 00:50:56:be:28:a5;
 fixed-address 10.0.0.203;
}

host ocp-w-1 {
 hardware ethernet 00:50:56:be:e4:45;
 fixed-address 10.0.0.211;
}

host ocp-w-2 {
 hardware ethernet 00:50:56:be:22:10;
 fixed-address 10.0.0.212;
}
host ocp-w-3 {
 hardware ethernet 00:50:56:bd:89:08;
 fixed-address 10.0.0.213;
}
