apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUX_TOKEN: U3RZRUZTTUNrRXJJcjgyQlRDYmxxd0g3eHdTMEhHQjVNYVh6NG1mRWIxcnZnNnNGRDdLUkxPd2F2SnhDaDcwU3kzbmpabG9hYmc1X0l0cEVrdm9jUVE9PQo=
