apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-data
spec:
  # volumeName: nfs-pv-a
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-config
spec:
  # volumeName: nfs-pv-b
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
