apiVersion: v1
kind: Secret
metadata:
  name: influxdb2-secrets
type: Opaque
data:
  influxdb2-admin-username: YWRtaW4K
  influxdb2-admin-password: cGFzc3dvcmQK
  influxdb2-admin-token: c1k0MWttZ0w1bjB2WmNhUzlTTm5kWkFsYWVIbm9nWkFpZmNUNTQxYTlhM0RDYThCSHBLUUpKc3J5OWNITE02ZnBncS1uM1VibnhwZUQ4ZkZYdFNpX3c9PQo=
